name: sonarqube
description: "Run SonarQube Cloud Scan"
inputs:
  args:
    description: "Arguments for SonarQube scan"
    required: false
  projectBaseDir:
    description: "Project base directory"
    required: false
runs:
  using: "composite"
  steps:
    - name: SonarQube Cloud Scan
      uses: SonarSource/sonarqube-scan-action@v4.2.1
      with:
        args: ${{ inputs.args }}
        projectBaseDir: ${{ inputs.projectBaseDir }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
