apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: actions-runner-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - secrets
      - services
      - namespaces
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
