name: kustomize-overlay-multi
description: Kustomize Overlay in GitHub

inputs:
  component-name:
    description: "Component name"
    required: true

  component-modules:
    description: "Component modules to update (list, JSON)"
    required: false
    default: ""

  component-overlays:
    description: "Overlays to update (list, JSON)"
    required: true

  component-tag:
    description: "New component tag"
    required: true

  kustomize-repo:
    description: kustomize repository
    required: true

  kustomize-access-token:
    description: kustomize access PAT
    required: true

runs:
  using: composite
  steps:
    - name: Checkout Kustomize
      uses: actions/checkout@v3
      with:
        path: kustomize
        repository: ${{ inputs.kustomize-repo }}
        ref: master
        token: ${{ inputs.kustomize-access-token }}

    - name: Update kustomize Overlay
      shell: bash -l -ET -eo pipefail {0}
      run: |
        hawk.setup.git

        cd kustomize

        overlays=$(util.ja2ba '${{ inputs.component-overlays }}')
        modules=$(util.ja2ba '${{ inputs.component-modules }}')

        COMMIT_MSG="AUTOMATIC COMMIT: Update of ${{ inputs.component-name }} to ${{ inputs.component-tag }} for ${overlays}"

        for overlay in ${overlays}; do
          for module in ${modules}; do
            HAWK_IMAGE_NAME=$(hawk.get-component-image ${{ inputs.component-name }} hawk ${module})
            KUSTOMIZE_PATH=$(hawk.get-component-kustomize-path ${{ inputs.component-name }} hawk ${module})

            echo "Updating ${KUSTOMIZE_PATH}/overlays/${overlay} for ${{ inputs.component-name }} to ${{ inputs.component-tag }}"

            (
              cd ${KUSTOMIZE_PATH}/overlays/${overlay}
              kustomize edit set image ${HAWK_IMAGE_NAME}:${{ inputs.component-tag }}
            )
          done
        done

        if [[ -z $(git status -s) ]]; then
          workflow.notice "no changes in overlays ${overlays}"
        else
          git diff
          git commit -a -m "${COMMIT_MSG}" -m "Workflow: ${HAWK_WORKFLOW_ID}" || workflow.die "failed to commit overlay changes"
        fi

        hawk.git-push || workflow.die "failed to push overlay changes"

# End of file
