name: job-init
description: Job Init Action

runs:
  using: composite
  steps:
    - name: Copy profile
      shell: bash -l -eo pipefail {0}
      run: |
        cp ${GITHUB_ACTION_PATH}/.bash_profile ${HOME}/.bash_profile

    - id: init
      shell: bash -l -eo pipefail {0}
      run: hawk.job-init

    - name: Simulate running a step against prechecks
      id: precheck
      shell: bash -l -eo pipefail {0}
      run: hawk.runner-prechecks