name: vulnerability-check
description: Vulnerability check

inputs:
  ecr-region:
    description: "ECR region"
    required: true

  ecr-registry-code:
    description: "ECR registry code"
    required: true

  image-name:
    description: "Name of image"
    required: true

  image-tag:
    description: "Tag of image"
    required: true

  ecr-url:
    description: "URL to ECR"
    required: true

  aws-access-key-id:
    description: "AWS access key id"
    required: true

  aws-secret-access-key:
    description: "AWS secret access key"
    required: true

  java-offline-mode:
    description: "Java offline mode"
    required: true

runs:
  using: composite
  steps:
    - name: Placeholder for future vulnerability check
      run: echo "Future vulnerability checks to go here"

    #- name: Configure AWS credentials
    #  uses: aws-actions/configure-aws-credentials@v2
    #  with:
    #    aws-access-key-id: ${{ inputs.aws-access-key-id }}
    #    aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
    #    aws-region: ${{ inputs.ecr-region }}

    #- name: Login to Amazon ECR
    #  id: login-ecr
    #  uses: aws-actions/amazon-ecr-login@v2
    #  with:
    #    registries: ${{ inputs.ecr-registry-code }}

    #- name: Retrieve AWS ECR login password for vulnerability check
    #  shell: bash -l -ET -eo pipefail {0}
    #  id: ecr-password
    #  env:
    #    ECR_REGION: ${{ inputs.ecr-region }}
    #  run: |
    #    echo "password=$(aws ecr get-login-password --region ${ECR_REGION})" >> $GITHUB_OUTPUT

# End of file
