name: kustomize-sync-environment
description: Kustomize Sync Environments

inputs:
  environment:
    description: "Environments to sync"
    required: true
  directories:
    description: "List of directories to sync environments in (separated by a space)"
    required: true
  github-token:
    description: "GitHub Token for authentication"
    required: true

runs:
  using: composite
  steps:
    - name: Checkout local repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install dotenv envsubst
    
    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Create feature branch
      id: branch
      shell: bash
      run: |
        BRANCH_NAME="sync-environments-$(date +%Y%m%d-%H%M%S)"
        git checkout -b "$BRANCH_NAME"
        echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
        echo "Created branch: $BRANCH_NAME"
    
    - name: Process environments
      shell: bash
      run: |
        set -e
        
        echo "Processing environment files from properties/static..."
        
        # Track if any changes were made
        CHANGES_MADE=false
        
        # Iterate through each file in properties/static directory
        env_name="${{ inputs.environment }}"
        env_file="properties/static/$env_name.env"
        if [ -f "$env_file" ]; then
          # Get the base filename (e.g., "sandbox.env")
          filename=$(basename "$env_file")
          
          echo ""
          echo "=========================================="
          echo "Processing environment: $env_name"
          echo "=========================================="
          
          # Make the output json into an env format and 
          # concat the env file to working directory as .env
          output_file="properties/output/${env_name}.json"
          if [ -f "$output_file" ]; then
            jq -r '[paths(scalars) as $path | {"key": $path | join("."), "value": getpath($path)}] | from_entries | to_entries[] | "\(.key | gsub("[\\.-]"; "_"))=\"\(.value)\""' "$output_file" \
              | fgrep '_value' \
              |  sed -E 's/\_value//' \
              | cat - $env_file > .env
          else
            cp "$env_file" .env
          fi
          
          
          for dir in ${{ inputs.directories }}; do
            if [ -d "$dir" ]; then
              echo "--- Processing platform directory ---"
              python3 ${{ github.action_path }}/copy_environment.py "$dir"
              echo "-------------------------------------"
              echo ""
            fi
          done
          
          echo ""
          echo "Completed processing for environment: $env_name"
        fi
        
        echo ""
        echo "=========================================="
        echo "All environments processed"
        echo "=========================================="
        
        # Save status for next step
        if [ -n "$(git status --porcelain)" ]; then
          echo "has_changes=true" >> $GITHUB_ENV
        else
          echo "has_changes=false" >> $GITHUB_ENV
        fi
    
    - name: Commit and push changes
      if: env.has_changes == 'true'
      shell: bash
      run: |
        
        echo "Changes detected, creating commit..."
        
        git add -A
        git commit -m "Sync environments from kustomize-template

        Auto-generated commit from kustomize-template repository.
        
        Processed environments:
        $(ls -1 properties/static/ | sed 's/^/  - /' | sed 's/\.env$//')
        
        Commit: ${{ github.sha }}
        Triggered by: ${{ github.actor }}"
        
        echo "Pushing branch to remote..."
        git push origin "${{ steps.branch.outputs.branch_name }}"
    
    - name: Create Pull Request
      if: env.has_changes == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        echo "Creating pull request..."
        gh pr create \
          --title "🔄 Sync environment ${{ inputs.environment}} from template" \
          --body "## Automated Environment Sync

        This PR was automatically generated by the sync workflow in the kustomize-template repository.

        ### Source Information
        - **Repository**: ${{ github.repository }}
        - **Commit**: ${{ github.sha }}
        - **Triggered by**: ${{ github.actor }}
        - **Workflow**: ${{ github.workflow }}

        ### Environments Processed
        $(ls -1 properties/static/ | sed 's/^/- /' | sed 's/\.env$//')

        ### Changes
        This PR includes updates to the following directories:
        - \`plattform/\` - Application services and configurations
        - \`kafka-management/\` - Kafka topic definitions

        All \`_template\` overlay directories have been expanded for the environments from \`properties/static/\`.

        ### Review Checklist
        - [ ] Verify kustomization.yaml paths are correct
        - [ ] Check image tags are appropriate for each environment
        - [ ] Validate environment-specific configurations
        - [ ] Ensure Kafka topic configurations are correct

        ---
        *This is an automated pull request. Review carefully before merging.*" \
          --base master \
          --head "${{ steps.branch.outputs.branch_name }}"
        
        echo "✅ Pull request created successfully!"
    
    - name: Cleanup on no changes
      if: env.has_changes == 'false'
      shell: bash
      run: |
        echo "ℹ️  No changes detected. Cleaning up branch."
        git checkout master
        git branch -D "${{ steps.branch.outputs.branch_name }}" || true
