name: kustomize-overlay
description: Kustomize Overlay

inputs:
  component-name:
    description: "Component name"
    required: true

  component-metadata:
    description: "Component metadata"
    required: true

  component-overlay:
    description: "Overlay to update"
    required: true
  
  component-tag:
    description: "New component tag"
    required: true
  
  kustomize-repo:
    description: kustomize repository
    required: true

  kustomize-access-token:
    description: kustomize access PAT
    required: true

runs:
  using: composite
  steps:
    - name: Get Hawk Image Name
      id: get-hawk-image-name
      uses: hawk-ai-aml/github-actions/get-component-image@python
      with:
        profile: hawk
        component: ${{ inputs.component-name }}

    # https://hawkai.atlassian.net/browse/SRE-629
    # this relies that all nab overlays are called nab-dev
    # nicer way is to pass profile, than evaluating overlay
    - name: Get NAB Image Name
      id: get-nab-image-name
      if: inputs.component-overlay == 'nab-dev'
      uses: hawk-ai-aml/github-actions/get-component-image@python
      with:
        profile: nab
        component: ${{ inputs.component-name }}

    - name: Checkout Kustomize
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.kustomize-repo }}
        ref: master
        token: ${{ inputs.kustomize-access-token }}

    - name: Update kustomize Overlay
      shell: bash
      env:
        HAWK_IMAGE_NAME: ${{ steps.get-hawk-image-name.outputs.image-name }}
        NAB_IMAGE_NAME: ${{ steps.get-nab-image-name.outputs.image-name }}
        KUSTOMIZE_PATH: ${{ fromJson(inputs.component-metadata).kustomize.path }}
        OVERLAY: ${{ inputs.component-overlay }}
      run: |
        cd ${KUSTOMIZE_PATH}/overlays/${OVERLAY}
        # https://hawkai.atlassian.net/browse/SRE-629
        # this relies that all nab overlays are called nab-dev
        # nicer way is to pass profile, than evaluating overlay
        if [[ ${OVERLAY} == 'nab-dev' ]]; then
          kustomize edit set image ${HAWK_IMAGE_NAME}=${NAB_IMAGE_NAME}:${{ inputs.component-tag }}
        else
          kustomize edit set image ${HAWK_IMAGE_NAME}:${{ inputs.component-tag }}
        fi
        if ! git diff --quiet HEAD; then
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@hawk.ai"
          git add .
          git commit -m "AUTOMATIC COMMIT: Update ${KUSTOMIZE_PATH}/overlays/${OVERLAY} for ${{ inputs.component-name }} to ${{ env.HAWK_IMAGE_TAG }}"
          git push
        fi
