name: kustomize-overlay
description: Kustomize Overlay

inputs:

  overlays:
    description: "List of overlay in string"
    required: true

  kustomize-access-token:
    description: "Kustomize access PAT"
    required: true

  kustomize-repo:
    description: "Kustomize repository"
    required: true

  component-tag:
    description: "New component tag"
    required: true

runs:
  using: composite
  steps:

    - name: Checkout Kustomize
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.kustomize-repo }}
        ref: master
        token: ${{ inputs.kustomize-access-token }}

    - name: Update
      shell: bash -l -ET -eo pipefail {0}
      env:
        OVERLAYS: ${{ inputs.overlays }}
        TAG: ${{ inputs.component-tag }}
      run: |
            KUSTOMIZE_PATH="plattform/case-manager/frontend"
            IMAGE_NAME="860641649575.dkr.ecr.eu-central-1.amazonaws.com/hawkai-case-manager-frontend"

            for overlay in $OVERLAYS; do
              KUSTOMIZE_OVERLAY_PATH=${KUSTOMIZE_PATH}/overlays/${overlay}

              # Get the current tag from kustomize rendered output
              current_tag=$(kustomize build "$KUSTOMIZE_OVERLAY_PATH" | grep -E "${IMAGE_NAME}:" | awk -F':' '{print $NF}' | tr -d '[:space:]')

              # Function to compare semantic versions
              compare_versions() {
                # Returns 0 if $1 >= $2, otherwise returns 1
                [ "$(printf '%s\n' "$1" "$2" | sort -V | head -n 1)" != "$1" ]
              }

              (
                cd ${KUSTOMIZE_OVERLAY_PATH}
                # Check if the new tag is greater than the current tag
                if compare_versions "$TAG" "$current_tag"; then
                    echo "Updated overlay ${overlay} of ${ECR_REPOSITORY} from $current_tag to ${TAG}"
                else
                    echo "No update needed. Current tag '$current_tag' is equal to or newer than '$TAG'."
                fi
              )
            done
