name: wiz-check
description: Vulnerability scan using Wiz CLI

inputs:
  ecr-region:
    description: "ECR region"
    required: true

  ecr-registry-code:
    description: "ECR registry code"
    required: true

  ecr-repository:
    description: "ECR repository"
    required: true

  image-tag:
    description: "Tag of image"
    required: true

  aws-access-key-id:
    description: "AWS access key id"
    required: true

  aws-secret-access-key:
    description: "AWS secret access key"
    required: true

  wiz-client-id:
    description: "Wiz Client ID"
    required: true

  wiz-client-secret:
    description: "Wiz Client Secret"
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.ecr-region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registries: ${{ inputs.ecr-registry-code }}

    - name: Install latest Wiz CLI
      shell: bash -l -ET -eo pipefail {0}
      run: |
        mkdir -p $HOME/.local/bin
        curl -fsSL https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64 -o $HOME/.local/bin/wizcli
        chmod +x $HOME/.local/bin/wizcli
        $HOME/.local/bin/wizcli version

    - name: Wiz CLI Auth
      shell: bash -l -ET -eo pipefail {0}
      env:
        WIZ_CLIENT_ID: ${{ inputs.wiz-client-id }}
        WIZ_CLIENT_SECRET: ${{ inputs.wiz-client-secret }}
      run: wizcli auth

    - name: Scan Docker image with Wiz
      shell: bash -l -ET -eo pipefail {0}
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.ecr-repository }}
        IMAGE_TAG: ${{ inputs.image-tag }}
      run: |
        IMAGE_PATH=${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
        wizcli docker scan --image "$IMAGE_PATH"

# End of file
