name: wiz-check
description: Vulnerability scan using Wiz CLI

inputs:
  ecr-region:
    description: "ECR region"
    required: true

  ecr-registry-code:
    description: "ECR registry code"
    required: true

  images:
    description: "List of Docker image names"
    required: true

  aws-access-key-id:
    description: "AWS access key id"
    required: true

  aws-secret-access-key:
    description: "AWS secret access key"
    required: true

  wiz-client-id:
    description: "Wiz Client ID"
    required: true

  wiz-client-secret:
    description: "Wiz Client Secret"
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.ecr-region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registries: ${{ inputs.ecr-registry-code }}

    - name: Install Wiz CLI
      shell: bash -l -ET -eo pipefail {0}
      run: |
        curl -o wizcli https://downloads.wiz.io/v1/wizcli/latest/wizcli-linux-amd64
        chmod +x wizcli
        sudo mv wizcli /usr/local/bin/
        wizcli version

    - name: Scan Docker image with Wiz
      shell: bash -l -ET -eo pipefail {0}
      env:
        IMAGES: ${{ inputs.images }}
        POLICIES: "BBK vulnerabilities policy"
        WIZ_CLIENT_ID: ${{ inputs.wiz-client-id }}
        WIZ_CLIENT_SECRET: ${{ inputs.wiz-client-secret }}
      run: |        
        for image in $IMAGES; do
          echo "Scan vulnerabilities for image: $image"
          docker pull $image
          wizcli scan container-image "$image" --policies "$POLICIES" --client-id "$WIZ_CLIENT_ID" --client-secret "$WIZ_CLIENT_SECRET"
          echo "-------------------------------"
        done

# End of file
