name: kustomize-overlay-ssh-multi
description: Kustomize Overlay in BitBucket

inputs:
  component-name:
    description: "Component name"
    required: true

  component-modules:
    description: "Component modules to update (JSON)"
    required: false
    default: ""

  component-overlays:
    description: "Overlays to update (list, JSON)"
    required: true
  
  component-tag:
    description: "New component tag"
    required: true

  kustomize-repo:
    description: kustomize repository
    required: true

  kustomize-ssh-key:
    description: kustomize RW access SSH key
    required: true

runs:
  using: composite
  steps:
    - name: Update kustomize Overlay
      shell: bash -l -eo pipefail {0}
      env:
        KUSTOMIZE_SSH_KEY_FILE: /home/builder/.ssh/id_kustomize_private_key
        KUSTOMIZE_SSH_KEY: ${{ inputs.kustomize-ssh-key }}
        OVERLAY: ${{ inputs.component-overlay }}
      run: |
        # Prepare SSH
        mkdir -p $(dirname ${KUSTOMIZE_SSH_KEY_FILE})
        echo ${KUSTOMIZE_SSH_KEY} | base64 -d > ${KUSTOMIZE_SSH_KEY_FILE}
        chmod 600 ${KUSTOMIZE_SSH_KEY_FILE}
        export GIT_SSH_COMMAND="ssh -i ${KUSTOMIZE_SSH_KEY_FILE}"
        cat <<EOF >> ~/.ssh/known_hosts
        bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
        github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
        EOF
        # End prepare SSH

        git clone ${{ inputs.kustomize-repo }} kustomize
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@hawk.ai"

        for module in ${{ inputs.component-modules }}; do
          for overlay in ${{ inputs.component-overlays }}; do
            HAWK_IMAGE_NAME=$(hawk.get-component-image ${{ inputs.component-name }} hawk )
            NAB_IMAGE_NAME=$(hawk.get-component-image ${{ inputs.component-name }} nab ${{ inputs.component-module }})
            KUSTOMIZE_PATH=$(hawk.get-component-kustomize-path ${{ inputs.component-name }} hawk ${{ inputs.component-module }})
            
            (
              cd kustomize/${KUSTOMIZE_PATH}/overlays/${overlay}

              # https://hawkai.atlassian.net/browse/SRE-629
              # this relies that all nab overlays are called nab-dev
              # nicer way is to pass profile, than evaluating overlay
              if [[ ${overlay} == 'nab-dev' ]]; then
                kustomize edit set image ${HAWK_IMAGE_NAME}=${NAB_IMAGE_NAME}:${{ inputs.component-tag }}
              else
                kustomize edit set image ${HAWK_IMAGE_NAME}:${{ inputs.component-tag }}
              fi

              git commit -m "AUTOMATIC COMMIT: Update ${KUSTOMIZE_PATH}/overlays/${overlay} for ${{ inputs.component-name }} to ${{ inputs.component-tag }}"
            )
          done
        done

        if ! git diff --quiet HEAD; then
          git push
        fi
