name: upload-to-s3
description: upload to s3

inputs:
  module:
    description: "Name of module"
    required: false
  source_dir:
    description: "Source directory from local"
    required: true
  destination_dir:
    description: "Destination directory on S3 bucket"
    required: true
  aws_bucket:
    description: "Name of S3 bucket"
    required: true
  aws_access_key_id:
    description: "AWS access key id"
    required: true
  aws_secret_access_key:
    description: "AWS secret access key"
    required: true

runs:
  using: composite
  steps:
    - name: Install AWS CLI
      uses: unfor19/install-aws-cli-action@v1
      with:
        version: 2

    - name: Set up secret file
      shell: bash -l -ET -eo pipefail {0}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
      run: |
        echo $AWS_ACCESS_KEY_ID >> secrets.txt
        echo $AWS_SECRET_ACCESS_KEY >> secrets.txt

    - name: Upload to S3
      id: upload
      shell: bash -l -ET -eo pipefail {0}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        MODULE: ${{ inputs.module }}
        BUCKET_NAME: ${{ inputs.aws_bucket }}
        SOURCE_DIR: ${{ inputs.source_dir }}
        DESTINATION_DIR: ${{ inputs.destination_dir }}
        AWS_DEFAULT_REGION: eu-central-1
      run: |
        sleep 500
        cd ${SOURCE_DIR}
        S3_DESTINATION_DIR=${DESTINATION_DIR}
        if [[ ${MODULE} != null ]]; then
          S3_DESTINATION_DIR=${DESTINATION_DIR}/${MODULE}
        fi

        aws s3api put-object --bucket ${BUCKET_NAME} --key ${S3_DESTINATION_DIR} --content-length 0
        aws s3 cp . s3://${BUCKET_NAME}/${S3_DESTINATION_DIR} --recursive

        if [[ ${MODULE} != null ]]; then
          HTML_FILES=$(aws s3 ls s3://${BUCKET_NAME}/${S3_DESTINATION_DIR} --recursive | awk '{$1=$2=$3=""; print $0}' | sed 's/^[ \t]*//' | grep "${MODULE}" | grep "index.html\|main.html\|licenseReport.html\|report.html")
        else
          HTML_FILES=$(aws s3 ls s3://${BUCKET_NAME}/${S3_DESTINATION_DIR} --recursive | awk '{$1=$2=$3=""; print $0}' | sed 's/^[ \t]*//' | grep "index.html\|main.html\|licenseReport.html\|report.html")
        fi

        REPORT_URL=https://${BUCKET_NAME}.s3.amazonaws.com/
        REPLACER="$DESTINATION_DIR\/"
        if [[ ${MODULE} != null ]]; then
          REPLACER="$DESTINATION_DIR\/$MODULE"
        fi

        echo "### Test Reports" | tee -a ${GITHUB_STEP_SUMMARY}
        for file in $HTML_FILES; do
          FULL_URL="${REPORT_URL}$file"
          DISPLAY_TEXT=$(echo $file | sed "s/$REPLACER//")
          echo "* [${DISPLAY_TEXT}](${FULL_URL})" | tee -a ${GITHUB_STEP_SUMMARY}
        done
# End of file
