name: upload-to-s3
description: upload to s3

inputs:
  source_dir:
    description: "Source directory from local"
    required: true
  destination_dir:
    description: "Destination directory on S3 bucket"
    required: true
  aws_bucket:
    description: "Name of S3 bucket"
    required: true
  aws_access_key_id:
    description: "AWS access key id"
    required: true
  aws_secret_access_key:
    description: "AWS secret access key"
    required: true

runs:
  using: composite
  steps:
    - name: Install AWS CLI
      uses: unfor19/install-aws-cli-action@v1
      with:
        version: 2

    - name: Upload to S3
      id: upload
      shell: bash -l -ET -eo pipefail {0}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        BUCKET_NAME: ${{ inputs.aws_bucket }}
        SOURCE_DIR: ${{ inputs.source_dir }}
        DESTINATION_DIR: ${{ inputs.destination_dir }}
      run: |
        echo "### Test Reports" | tee -a ${GITHUB_STEP_SUMMARY}
# End of file
