name: check-docker-tag-exists
description: Check if the docker tag exists or not

inputs:
  ecr-registry:
    description: "URI of the ecr registry"
    required: true
  ecr-repository:
    description: "Name of the ECR repository"
    required: true
  image-tag:
    description: "Repository access token"
    required: true

outputs:
  updatedModules:
    description: 'The list of modules has the code changes'
    value: ${{ steps.check-tag.outputs.updatedModules }}

  tag_exists:
    description: 'The list of modules has the code changes in string'
    value: ${{ steps.check-tag.outputs.tag_exists }}

runs:
  using: composite
  steps:
    - shell: bash -l -ET -eo pipefail {0}
      id: check-tag
      env:
        ECR_REGISTRY: ${{ inputs.ecr-registry }}
        IMAGE_TAG: ${{ inputs.image-tag }}
      run: |

        # Extract the repository name using jq
        ECR_REPOSITORY=$(echo '${{ inputs.ecr-repository }}' | jq -r '.repository')

        # Check if docker tag already exists
        docker_pull_output=$(docker pull "${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}" 2>&1 || echo "")
        echo $docker_pull_output

        # Pull the Docker image
        echo "tag_exists=$(echo $docker_pull_output | grep -q 'not found' && echo 'false' || echo 'true')" >> $GITHUB_OUTPUT

        # Workflow outputs
        cat <<EOF | tee -a ${GITHUB_STEP_SUMMARY} | tee -a ${GITHUB_OUTPUT}
        updatedModules="whatup"
        EOF
