# Deprecated, use library function

name: get-component-image
description: Get Component Image for specific profile

inputs:
  component:
    description: "Component to retrieve metadata"
    required: true

  module:
    description: "Component module to retrieve metadata"
    required: false
    default: ""

  profile:
    description: Metadata profile
    required: false
    default: hawk

outputs:
  image-name:
    description: 'Component image name'
    value: ${{ steps.vars.outputs.image-name }}

  kustomize-path:
    description: 'Component kustomize path'
    value: ${{ steps.vars.outputs.kustomize-path }}

runs:
  using: composite
  steps:
    - id: vars
      shell: bash -l -ET -eo pipefail {0}
      run: |
        IMAGE_NAME=$(hawk.get-component-image ${{ inputs.component }} ${{ inputs.profile }} ${{ inputs.module }} || workflow.die "cannot get image")
        KUSTOMIZE_PATH=$(hawk.get-component-kustomize-path ${{ inputs.component }} ${{ inputs.profile }} ${{ inputs.module }} || workflow.die "cannot get kustomize path")
        echo "image-name=${IMAGE_NAME}" >> ${GITHUB_OUTPUT}
        echo "kustomize-path=${KUSTOMIZE_PATH}" >> ${GITHUB_OUTPUT}

# End of file
