name: add-gitops-tag

on:
  workflow_call:
    inputs:
      tag:
        type: string
        description: Tag name
        required: true
      description:
        type: string
        description: Description for the release
        required: false
      overlay:
        type: string
        description: Gitops overlay will be updated
        required: false
jobs:
  tag:
    runs-on: [ "self-hosted", "builder" ]

    steps:
      - id: init
        name: Init Job
        uses: hawk-ai-aml/github-actions/job-init@master
        with:
          slack-notification-webhook: ${{ secrets.CICD_MIGRATION_SLACK_WEBHOOK_URL }}

      - name: Checkout Kustomize
        uses: actions/checkout@v3
        with:
          repository: hawk-ai-aml/kustomize.git
          ref: master
          token: ${{ secrets.REPO_ACCESS_PAT }}

      - name: Checkout Gitops
        uses: actions/checkout@v3
        with:
          path: gitops
          repository: hawk-ai-aml/gitops.git
          ref: master
          token: ${{ secrets.REPO_ACCESS_PAT }}

      - name: Update targetRevision for ${{ inputs.overlay }} overlay
        shell: bash -l -ET -eo pipefail {0}
        run: |
          hawk.setup.git

          cd gitops

          for f in overlays/${{ inputs.overlay }}/*
          do
            if [ ${f} != "overlays/${{ inputs.overlay }}/kustomization.yaml" ]; then
              echo Set Tag for ${f}
              kubectl patch --local -f ${f} -p '{"spec":{"source":{"targetRevision":"'${{ inputs.tag }}'"}}}' --type merge -o yaml > overlay.tmp && mv overlay.tmp ${f}
          fi
          done

          if [[ -z $(git status -s) ]]; then
            echo "No changes in ${{ inputs.overlay }} overlay"
          else
            git diff
            git add .
            git commit -am "${{ inputs.description }}"
            git push --set-upstream origin master
          fi