name: build

on:
  workflow_call:
    inputs:
      updateKustomize:
        description: "Update kustomize overlays"
        type: boolean
        required: false
      kustomizeOverlays:
        description: "Overlays to update"
        type: string
        required: false
      component:
        type: string
        required: false
      deleteCache:
        type: boolean
        required: false
      vulnerabilityCheck:
        description: "Conduct a vulnerability check using Lacework"
        type: boolean
        required: false
        default: false

defaults:
  run:
    shell: bash -l -ET -eo pipefail {0}

jobs:
  init:
    runs-on: [ "self-hosted", "small-builder" ]
    outputs:
      overlays: ${{ steps.init.outputs.overlays }}
      metadata: ${{ steps.init.outputs.metadata }}
      update-kustomize: ${{ steps.init.outputs.update-kustomize }}
      image-tag: ${{ steps.init.outputs.image-tag }}
      kustomize-modules: ${{ steps.init.outputs.kustomize-modules }}
      kustomize-modules-string: ${{ steps.init.outputs.kustomize-modules-string }}
      ecr-url: ${{ steps.init.outputs.ecr-url }}
      ecr-registry-code: ${{ steps.init.outputs.ecr-registry-code }}
      ecr-region: ${{ steps.init.outputs.ecr-region }}
      ecr-images: ${{ steps.init.outputs.ecr-images }}
      custom-tags: ${{ steps.custom-tags.outputs.custom_tags }}

    steps:
      - id: init
        name: Init Workflow
        uses: hawk-ai-aml/github-actions/workflow-init@master
        with:
          update-kustomize: ${{ inputs.updateKustomize }}
          overlays: ${{ inputs.kustomizeOverlays }}
          repository-name: hawk-ai-aml/${{ inputs.component }}
          repository-ref: ${{ env.GITHUB_REF_NAME }}
          repository-access-token: ${{ secrets.REPO_ACCESS_PAT }}

      - id: custom-tags
        name: Generate a list of Docker tags for all modules
        env:
          ECR_REPOSITORIES: ${{ steps.init.outputs.ecr-repositories }}
          IMAGE_TAG: ${{ steps.init.outputs.image-tag }}
        run: |
          CUSTOM_TAGS=""
          for repo in $ECR_REPOSITORIES; do
            NEW_TAG=${repo}-${IMAGE_TAG}
            CUSTOM_TAGS="$CUSTOM_TAGS $NEW_TAG"
          done
          echo "custom_tags=$CUSTOM_TAGS" >> $GITHUB_OUTPUT

      - name: Update Jira ticket labels
        if: ${{ github.workflow == 'pr' }}
        uses: hawk-ai-aml/github-actions/update-jira-ticket-label@master
        continue-on-error: true
        with:
          repository: ${{ inputs.component }}
          github-branch: ${{ github.head_ref }}
          pr-title: ${{ github.event.pull_request.title }}
          modules-string: ""
          multiple-modules: "false"
          jira-user: ${{ secrets.JIRA_ACCOUNT_NAME }}
          jira-token: ${{ secrets.JIRA_TOKEN }}


  setup-and-lint:
    needs: [ init ]
    runs-on: [ "self-hosted", "small-builder" ]
    outputs:
      node-module-cache-key: ${{ steps.cache-key.outputs.node-module-cache-key }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '^22.12.0'

      - name: Generate cache key
        id: cache-key
        run: |
          echo "node-module-cache-key=${{ runner.os }}-module-${{ hashFiles('**/yarn.lock') }}" >> $GITHUB_OUTPUT

      - name: Node module cache
        uses: actions/cache@v3
        id: module-cache
        with:
          path: |
            **/node_modules
          key: ${{ steps.cache-key.outputs.node-module-cache-key }}
          restore-keys: ${{ runner.os }}-module-

      - name: Install node modules
        if: steps.module-cache.outputs.cache-hit != 'true'
        run: yarn run yarn:install

      - name: Build license report
        run: ./node_modules/license-checker/bin/license-checker > licenseReport.txt

      - name: Lint check
        run: yarn run prettier:check


  tests:
    needs: [ init, setup-and-lint ]
    runs-on: [ "self-hosted", "frontend-builder" ]

    strategy:
      matrix:
        shard: [1, 2, 3, 4]
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 1000

      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_REF_NAME }}
          fetch-depth: 1000

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '^22.12.0'

      - name: Node modules cache
        uses: actions/cache@v3
        id: module-cache
        with:
          path: |
            **/node_modules
          key: ${{ needs.setup-and-lint.outputs.node-module-cache-key }}
          restore-keys: ${{ runner.os }}-module-

      - name: Install node modules
        if: steps.module-cache.outputs.cache-hit != 'true'
        run: yarn run yarn:install

      - name: Yarn test
        run: yarn run test:ci --shard=${{ matrix.shard }}/${{ strategy.job-total }}

  build:
    needs: [ init, setup-and-lint, tests ]
    runs-on: [ "self-hosted", "frontend-builder" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '^22.12.0'

      - name: SonarQube Cloud Scan
        if: ${{ github.workflow == 'pr' }}
        uses: hawk-ai-aml/github-actions/sonarqube@master
        with:
          sonarToken: ${{ secrets.SONAR_TOKEN }}
          sonarHostUrl: ${{ secrets.SONAR_HOST_URL }}

      - name: Node module cache
        uses: actions/cache@v3
        id: module-cache
        with:
          path: |
            **/node_modules
          key: ${{ needs.setup-and-lint.outputs.node-module-cache-key }}
          restore-keys: ${{ runner.os }}-module-

      - name: Install node modules
        if: steps.module-cache.outputs.cache-hit != 'true'
        run: yarn run yarn:install

      - name: Yarn build
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: yarn run build

      - name: Get ECR info
        id: ecr-info
        env:
          CUSTOM_TAGS: ${{ needs.init.outputs.custom-tags }}
          MODULE: ${{ inputs.component }}
        run: |
          MATCHED_TAG=$(echo "$CUSTOM_TAGS" | tr ' ' '\n' | grep -E "(^|[-])${MODULE}([-]|$)" | head -n 1 || true)
          echo "matched_tag=$MATCHED_TAG" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        if: ${{ github.workflow != 'pr' }}
        uses: hawk-ai-aml/github-actions/build-docker-image-reactjs@master
        with:
          image-tag: ${{ needs.init.outputs.image-tag }}
          custom-image-tag: ${{ steps.ecr-info.outputs.matched_tag }}
          ecr-registry: ${{ steps.login-ecr.outputs.registry }}
          ecr-repository: ${{ fromJson(needs.init.outputs.metadata).ecr.repository }}
          kustomize-overlays: ${{ inputs.kustomizeOverlays }}
          hawk-platform-repository: "hawk-platform"
          aws-org-ecr-access-key-id: ${{ secrets.AWS_ORG_ECR_ACCESS_KEY_ID }}
          aws-org-ecr-secret-access-key: ${{ secrets.AWS_ORG_ECR_SECRET_ACCESS_KEY }}
          ecr-region: ${{ needs.init.outputs.ecr-region }}
          ecr-registry-code: ${{ needs.init.outputs.ecr-registry-code }}

      - name: Slack notification for failed build status
        uses: hawk-ai-aml/github-actions/send-slack-notification@master
        if: failure()
        with:
          notify-pr-author: true
          slack-message: ":x: Your build failed. Please check the reason for it."
          slack-access-token: ${{ secrets.SLACK_RELEASE_BOT_ACCESS_TOKEN }}
          github-users-access-token: ${{ secrets.USER_GITHUB_ACCESS }}

  vulnerability-check-run:
    if: ${{ inputs.vulnerabilityCheck == true }}
    needs: [ init, build ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        image: ${{ fromJson(needs.init.outputs.ecr-images) }}

    steps:
      - name: Vulnerability check
        uses: hawk-ai-aml/github-actions/vulnerability-check@master
        with:
          ecr-region: ${{ needs.init.outputs.ecr-region }}
          ecr-registry-code: ${{ needs.init.outputs.ecr-registry-code }}
          image-name: ${{ matrix.image }}
          image-tag: ${{ needs.init.outputs.image-tag }}
          ecr-url: ${{ needs.init.outputs.ecr-url }}
          aws-access-key-id: ${{ secrets.AWS_ORG_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ORG_ECR_SECRET_ACCESS_KEY }}
          java-offline-mode: ${{ env.LACEWORK_JAVA_OFFLINE_MODE }}

  update-overlays:
    needs: [ init, setup-and-lint, tests, build ]
    if: ${{ needs.init.outputs.update-kustomize == 'true' && github.workflow != 'pr' }}
    runs-on: [ "self-hosted", "small-builder" ]

    steps:
      - name: Update kustomize overlay
        uses: hawk-ai-aml/github-actions/kustomize-overlay@master
        with:
          slack-access-token: ${{ secrets.SLACK_RELEASE_BOT_ACCESS_TOKEN }}
          github-users-access-token: ${{ secrets.USER_GITHUB_ACCESS }}
          overlays: ${{ needs.init.outputs.overlays }}
          kustomize-overlays: ${{ inputs.kustomizeOverlays }}
          modules: ${{ needs.init.outputs.kustomize-modules-string }}
          component-name: ${{ inputs.component }}
          component-tag: ${{ needs.init.outputs.image-tag }}
          component-custom-tags: ${{ needs.init.outputs.custom-tags }}
          kustomize-repo: hawk-ai-aml/kustomize.git
          kustomize-access-token: ${{ secrets.REPO_ACCESS_PAT }}
          ecr-region: ${{ needs.init.outputs.ecr-region }}
          ecr-registry-code: ${{ needs.init.outputs.ecr-registry-code }}
          metadata: ${{ needs.init.outputs.metadata }}

  clean-up:
    needs: [ init, setup-and-lint, tests, build ]
    runs-on: [ "self-hosted", "small-builder" ]

    steps:
      - uses: actions/checkout@v4

      - name: Clean cache
        if: ${{ inputs.deleteCache == true }}
        env:
          USER: ${{ secrets.RECREATE_DEVELOP_GITHUB_USER }}
          TOKEN: ${{ secrets.RECREATE_DEVELOP_GITHUB_TOKEN }}
          REPOSITORY: ${{ inputs.component }}
          CACHE_KEY: ${{ needs.setup-and-lint.outputs.node-module-cache-key }}
        run: |
          chmod +x ./lib/delete-cache.sh
          ./lib/delete-cache.sh
        shell: bash
