name: end-to-end-tests

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: Environment
        required: true

jobs:
  end-to-end-tests:
    runs-on: [ "self-hosted", "builder" ]
    steps:
      - name: Checkout E2E-Tests
        uses: actions/checkout@v3
        with:
          repository: hawk-ai-aml/end-to-end-tests.git
          token: ${{ secrets.REPO_ACCESS_PAT }}
          ref: ${{ inputs.environment }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Run end to end test
        env:
          AUTH0_DEV_API_CLIENT_SECRET: ${{ secrets.AUTH0_DEV_API_CLIENT_SECRET }}
          AUTH0_PROD_API_CLIENT_SECRET: ${{ secrets.AUTH0_PROD_API_CLIENT_SECRET }}
          AUTH0_PROD_US_EAST_API_CLIENT_SECRET: ${{ secrets.AUTH0_PROD_US_EAST_API_CLIENT_SECRET }}

          environment: ${{ inputs.environment }}
        run: |
          # sudo apt update
          # sudo apt-get -y install libnspr4 libnss3 libnss3-tools
          ./gradlew :demo:clean :demo:assemble :demo:testClasses -isS
          ./gradlew :demo:check -Denvironment=${{ inputs.environment }} -isS
          ls *
          ls ./demo/*
          ls ./demo/allure*

      - name: Copy result files for upload to GitHub Artifact
        run: |
          pwd
          mkdir github-artifact
          mv /home/runner/work/kustomize-cicd/kustomize-cicd/demo/build/reports/tests/* github-artifact

      - name: Upload plain test results to GitHub Artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results
          path: github-artifact

      - name: Upload Allure results to GitHub Artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results
          path: allure-reports

      - name: Upload Allure results to GitHub Artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: allure-results
          path: demo/allure-results
