name: ci-java

on:
  workflow_call:
    inputs:
      updateKustomize:
        description: "Update kustomize overlays (true/false)"
        type: boolean
        required: false
      skipTests:
        description: "Skip extended testing (unit and other tests), only build artifacts"
        type: boolean
        required: false
        default: false
      kustomizeOverlays:
        description: "The indicated overlays (dev, test, qa, prod)"
        type: string
        required: false
      component:
        description: "Name of the repository"
        type: string
        required: false
      base-tag:
        description: "This tag will be used in case we have a specific base image tag (now watchtower and label-engine only)"
        type: string
        required: false

defaults:
  run:
    shell: bash -l -ET -eo pipefail {0}

jobs:
  ci:
    runs-on: [ "self-hosted", "small-builder" ]

    steps:
      - name: Generate e2e tests metadata
        id: e2e-metadata
        uses: hawk-ai-aml/github-actions/e2e-tests-metadata@1468-test
        with:
          repository-access-token: ${{ secrets.REPO_ACCESS_PAT }}

      - name: Generate correlation id
        id: correlationId
        shell: bash -l -ET -eo pipefail {0}
        run: |
          RUN_ID=`date "+%Y%m%d-%H%M%S"`
          CORRELATION_ID="${{ github.actor }}-${RUN_ID}"
          echo "id=ci-test" >> $GITHUB_OUTPUT

      - name: Run e2e tests
        shell: bash -l -ET -eo pipefail {0}
        env:
          USER: ${{ secrets.RECREATE_DEVELOP_GITHUB_USER }}
          TOKEN: ${{ secrets.REPO_ACCESS_PAT }}
          METADATA: ${{ steps.e2e-metadata.outputs.metadata }}
          CORRELATION_ID: ${{ steps.correlationId.outputs.id }}
        run: |
          curl --silent -X POST "https://api.github.com/repos/hawk-ai-aml/end-to-end-tests/actions/workflows/test-e2e-demo-v2-tests.yaml/dispatches" -d "{\"ref\":\"feature/sre-1468\", \"inputs\": {\"metadata\": \"${METADATA}\", \"run-name\": \"${CORRELATION_ID}\"}}" -u "$USER:$TOKEN"

      - name: Check test results
        shell: bash -l -ET -eo pipefail {0}
        env:
          USER: ${{ secrets.RECREATE_DEVELOP_GITHUB_USER }}
          TOKEN: ${{ secrets.REPO_ACCESS_PAT }}
          CORRELATION_ID: ${{ steps.correlationId.outputs.id }}
        run: |
          sleep 60
          while true
          do
            echo "CORRELATION_ID=${CORRELATION_ID}"
            RUNS=$(curl -s "https://api.github.com/repos/hawk-ai-aml/end-to-end-tests/actions/runs?status=completed&per_page=100" -u "$USER:$TOKEN" | jq -r '.workflow_runs | [.[] | select(.name | contains('\"${CORRELATION_ID}\"')) | .name] | join(" ")')
          
            if [[ "$RUNS" != "" ]]; then
              break
            fi
          
            sleep 10
          done
          
          SUCCESS_TESTS=$(curl -s "https://api.github.com/repos/hawk-ai-aml/end-to-end-tests/actions/runs?per_page=100" -u "$USER:$TOKEN" | jq -r '.workflow_runs | [.[] | select(.name | contains('\"${CORRELATION_ID}\"')) | select(.status == "completed") | select(.conclusion == "success") | .name] | join(" ")')
          
          if [[ "$SUCCESS_TESTS" != "" ]]; then
            echo "All tests are green!"
          else
            echo "There are some failed tests. Please check."
          fi