name: ci-java

on:
  workflow_call:
    inputs:
      updateKustomize:
        description: "Update kustomize overlays (true/false)"
        type: boolean
        required: false
      skipTests:
        description: "Skip extended testing (unit and other tests), only build artifacts"
        type: boolean
        required: false
        default: false
      kustomizeOverlays:
        description: "The indicated overlays (dev, test, qa, prod)"
        type: string
        required: false
      component:
        description: "Name of the repository"
        type: string
        required: false
      base-tag:
        description: "This tag will be used in case we have a specific base image tag (now watchtower and label-engine only)"
        type: string
        required: false

defaults:
  run:
    shell: bash -l -ET -eo pipefail {0}

jobs:
  ci:
    runs-on: [ "self-hosted", "small-builder" ]

    steps:
      - name: Generate e2e tests metadata
        id: e2e-metadata
        uses: hawk-ai-aml/github-actions/e2e-tests-metadata@1468-test
        with:
          repository-access-token: ${{ secrets.REPO_ACCESS_PAT }}

      - name: Generate correlation id
        id: correlationId
        shell: bash -l -ET -eo pipefail {0}
        run: |
          RUN_ID=`date "+%Y%m%d-%H%M%S"`
          CORRELATION_ID="${{ github.actor }}-${RUN_ID}"
          echo "id=${CORRELATION_ID}" >> $GITHUB_OUTPUT

  e2e-tests:
    needs: ci
    runs-on: [ "self-hosted", "builder" ]
    strategy:
      fail-fast: false
      matrix:
        test: [ "amlcheck", "amnis" ]

    steps:
      - name: Run ${{ matrix.test }} test
        id: test
        uses: hawk-ai-aml/github-actions/build-e2e-test@1468-test
        with:
          environment: "test"
          test: ${{ matrix.test }}
          ref: "master"
          metadata: ${{ inputs.metadata }}
          repository-access-token: ${{ secrets.REPO_ACCESS_PAT }}
          auth0-dev-api-client-secret: ${{ secrets.AUTH0_DEV_API_CLIENT_SECRET }}
          auth0-prod-api-client-secret: ${{ secrets.AUTH0_PROD_API_CLIENT_SECRET }}
          auth0-prod-us-east-api-client-secret: ${{ secrets.AUTH0_PROD_US_EAST_API_CLIENT_SECRET }}
          auth0-prod-ap-southeast-api-client-secret: ${{ secrets.AUTH0_PROD_AP_SOUTHEAST_API_CLIENT_SECRET }}
          auth0-nab-qa-api-client-secret: ${{ secrets.AUTH0_PROD_US_EAST_API_CLIENT_SECRET }}
          auth0-nab-prod-api-client-secret: ${{ secrets.AUTH0_PROD_US_EAST_API_CLIENT_SECRET }}
          auth0-prod-ch-api-client-secret: ${{ secrets.AUTH0_PROD_CH_API_CLIENT_SECRET }}
          artifactory-context-url: ${{ secrets.ARTIFACTORY_CONTEXT_URL }}
          artifactory-username: ${{ secrets.ARTIFACTORY_USERNAME }}
          artifactory-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
          gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
          dev-redis-host: ${{ secrets.DEV_REDIS_HOST }}
          dev-redis-port: ${{ secrets.DEV_REDIS_PORT }}
          dev-redis-auth-token: ${{ secrets.DEV_REDIS_AUTH_TOKEN }}
          aws-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}

  deploy:
    needs: e2e-tests
    runs-on: [ "self-hosted", "builder" ]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: sre-test

      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: sre-test
          check-name: e2e-tests
          repo-token: ${{ secrets.REPO_ACCESS_PAT }}
          wait-interval: 10

      - name: Deploy
        run: |
          echo "Deploying {{ inputs.component }}"
