name: pr-labels
on:
  pull_request:
    branches:
      - master
      - main
    types:
      - labeled
      - unlabeled
      - synchronize
      - edited

jobs:
  enforce-label:
    runs-on: ["self-hosted", "small-builder"]
    steps:
      - name: check labels
        uses: hawk-ai-aml/github-actions/enforce-labels@master
        with:
          repository-ref: $GITHUB_REF
          repository-access-token: ${{ secrets.REPO_ACCESS_PAT }}
