name: Release

on:
  workflow_call:
    inputs:
      tag:
        type: string
        description: Tag to be used in the next release
        required: true
      environments:
        type: string
        description: Environments that this tags should be deployed to
        required: true
      tests-repository:
        type: string
        description: The repository where the end to end tests are to be found
        required: true
    secrets:
      token:
        required: true
      AUTH0_DEV_API_CLIENT_SECRET:
        required: true
      AUTH0_PROD_API_CLIENT_SECRET:
        required: true

jobs:

  release:
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        environment: ${{fromJson(inputs.environments)}}
    runs-on: ubuntu-22.04
    steps:
      - name: Sync Argo CD
        run: echo "Here we will refresh and sync Argo CD in the first environment"
      - name: Checkout E2E-Tests repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.tests-repository }}
          token: ${{ secrets.TOKEN }}
          ref: master
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: "Quality Gate 1: Run end to end test"
        env:
          AUTH0_DEV_API_CLIENT_SECRET: ${{ secrets.AUTH0_DEV_API_CLIENT_SECRET }}
          AUTH0_PROD_API_CLIENT_SECRET: ${{ secrets.AUTH0_PROD_API_CLIENT_SECRET }}
          environment: "dev"
        run: |
          ./gradlew :demo:clean :demo:assemble :demo:testClasses -isS
          ./gradlew :demo:check -Denvironment=${{ matrix.environment }} -isS