name: Create teleport user
on:
  workflow_call:
      inputs:
        cluster_teleport:
          description: "Address teleport cluster"
          type: string
          default: "teleport.dev.aml-ai.net"
          required: true
        OTP-admin:
          description: "Input OTP admin"
          type: string
          default: "123456"
          required: true
        user_name:
          description: "Create user name"
          type: string
          required: true
        user_role:
          description: "Assign roles to user"
          type: multi-choice
          options:
          - developer
          - admin
          - super-admin 
          required: true  
jobs:
  Create-user:
    name: Run create user
    runs-on: ubuntu-latest
    container: public.ecr.aws/gravitational/teleport:12.3.1
    steps:
      - uses: actions/checkout@v3
      - name: Check teleport version
        run: tctl version
      - name: Check teleport version 
        run: tsh version
      - name: login teleport cluster
        run: |
          expect << EOF
            spawn tsh login --proxy=${{ inputs.cluster_teleport }}  --user=admin
            expect "Enter password for Teleport user admin:"
            send "${{ secrets.ADMIN_PASSWORD }}\r"
            expect "Enter an OTP code from a device:"
            send "${{ inputs.OTP-admin }}\r"
            expect eof
          EOF
      - name: Verify login success
        run: tctl status 
      - name: Create user name
        run: tctl users add ${{ inputs.user_name }} --roles=${{ inputs.user_role }}
        id: user_name_info  
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: ${{join(steps.user_name_info.outputs.*, '\n')}}
          SLACK_TITLE: Send username info
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
