name: Create teleport user
on:
  workflow_call:
      inputs:
        cluster-teleport:
          description: "Name of cluster"
          type: choice 
          options:
          - dev-cluster
          - sgp-prod-cluster 
          required: true
        OTP-admin:
          description: "Input OTP admin"
          type: string
          required: true
        role_path:
          description: "Role path"
          type: string
          required: true
jobs:
  Create-user:
    name: Run create user
    runs-on: ubuntu-latest
    container: public.ecr.aws/gravitational/teleport:12.3.1
    steps:
      - name: Check teleport version
        run: tctl version
      - name: Check teleport version 
        run: tsh version
      - name: login teleport cluster
        run: |
          expect << EOF
          spawn tsh login --proxy=teleport.dev.aml-ai.net  --user=admin
          expect "Enter password for Teleport user admin:"
          send "${{ secrets.ADMIN_PASSWORD }}\r"
          expect "Enter an OTP code from a device:"
          send "${{ inputs.OTP-admin }}\r"
          expect eof
        EOF

      - name: Verify login success
        run: tctl status 
      - name: Create new roles
        run: tctl create -f ${{ inputs.role_path }}
      - name: Verify new roles
        run: tctl get roles --format text
        id: role_info  
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: ${{join(steps.user_name_info.outputs.*, '\n')}}
          SLACK_TITLE: Send username info
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}