name: test-get-component-image
on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - profile: test-hawk
            component: backend
            module: msg
            expected-image-name: 860641649575.dkr.ecr.eu-central-1.amazonaws.com/hawkai-case-manager-backend-msg
          - profile: test-hawk
            component: label-engine
            expected-image-name: 860641649575.dkr.ecr.eu-central-1.amazonaws.com/label-engine
          - profile: test-hawk
            component: secure-storage
            expected-image-name: 860641649575.dkr.ecr.eu-central-1.amazonaws.com/current-secure-storage
          - profile: test-nab
            component: label-engine
            expected-image-name: 569345997196.dkr.ecr.us-east-1.amazonaws.com/hawk-label-engine
          - profile: test-nab
            component: secure-storage
            expected-image-name: 569345997196.dkr.ecr.us-east-1.amazonaws.com/hawk-current-secure-storage

    steps:
      - id: init
        name: Get image name
        uses: hawk-ai-aml/github-actions/get-component-image@master
        with:
          profile: ${{ matrix.profile }}
          component: ${{ matrix.component }}
          module: ${{ matrix.module }}
      
      - id: show
        run: echo ${{ steps.init.outputs.image-name }} | tee -a ${GITHUB_STEP_SUMMARY}

      - id: assert
        name: Validate
        uses: actions/github-script@v3
        env:
          EXPECTED: ${{ matrix.expected-image-name }}
          ACTUAL: ${{ steps.init.outputs.image-name }}
        with:
          script: |
            const { EXPECTED, ACTUAL } = process.env
            if (EXPECTED != ACTUAL ) {
              core.setFailed(`
              Expected: ${EXPECTED}
              Actual:   ${ACTUAL}
              `)
            }

  test-missing-ecr-block:
    runs-on: ubuntu-22.04
    steps:
      - id: init
        name: Get image name
        uses: hawk-ai-aml/github-actions/get-component-image@master
        continue-on-error: true
        with:
          profile: test-hawk
          component: backend

      - id: assert-failure
        name: Validate
        uses: actions/github-script@v3
        if: always()
        env:
          OUTCOME: ${{ steps.init.outcome }}
        with:
          script: |
            const { OUTCOME } = process.env
            if (OUTCOME != 'failure') {
              core.setFailed('Expected failure, but got success')
            }
