name: update-dependencies
on:
  workflow_call:
    inputs:
      component:
        type: string
        required: true
      write-lock:
        type: string
        required: true
      label:
        type: string
        required: true

jobs:
  init:
    runs-on: [ "self-hosted", "builder" ]
    outputs:
      metadata: ${{ steps.init.outputs.metadata }}
    steps:
      - id: init
        name: Init Workflow
        uses: hawk-ai-aml/github-actions/workflow-init@master
        with:
          update-kustomize: false
          overlays: ${{ inputs.kustomizeOverlays }}
          repository-name: hawk-ai-aml/${{ inputs.component }}
          repository-access-token: ${{ secrets.REPO_ACCESS_PAT }}

  lock-dependencies:
    needs: [ init ]
    runs-on: [ "self-hosted", "builder" ]
    outputs:
      result: ${{ steps.commit-and-push.outputs.result }}
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ fromJson(needs.init.outputs.metadata).java-version }}
          distribution: temurin

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_ACCESS_PAT }}

      - name: Checkout update-dependencies
        run: git checkout -B update-dependencies

      - name: Perform dependency resolution and write new lockfiles
        run: |
          ${{ inputs.write-lock }}
          git status
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_CONTEXT_URL: ${{ secrets.ARTIFACTORY_CONTEXT_URL }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Commit, push, create pull request
        id: commit-and-push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@hawk.ai"
          git add .

          if ! git diff --quiet HEAD; then
            git commit -m "build(gradle): Update gradle.lockfile"
            git push --force origin update-dependencies
            echo "result=success" >> $GITHUB_OUTPUT
          else
            echo "result=skipped" >> $GITHUB_OUTPUT
            echo "no dynamic dependencies updates"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-pr:
    runs-on: [ "self-hosted", "builder" ]
    needs: [ init , lock-dependencies ]
    if: needs.lock-dependencies.outputs.result == 'success'
    steps:
      - name: Create pull request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const pr_list = await github.rest.pulls.list({
              owner,
              repo,
              head: 'hawk-ai-aml:update-dependencies',
              base: 'master'
            });

            console.log(pr_list)

            if (pr_list.data.length == 0) {
              const result = await github.rest.pulls.create({
                title: 'build(gradle): Update dependencies',
                owner,
                repo,
                head: 'update-dependencies',
                base: 'master',
                body: [
                  'Auto-generated dependency update'
                ].join('\n')
              });
              github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: result.data.number,
                labels: ['${{ inputs.label }}', 'patch-version', 'impact 1 * likelyhood 1 = risk 1']
              });
            }
          github-token: ${{ secrets.REPO_ACCESS_PAT }}
