name: Workflow Metrics Tests

on:
  pull_request:
    paths:
      - 'workflow-metrics/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run tests
        run: |
          cd workflow-metrics
          python -m unittest discover scripts/ -v
